/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/abcd.glb -o src/components/Eclat.jsx -k -K -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Eclat(props) {
  const { nodes, materials } = useGLTF('/models/abcd.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Roadmap" rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
          <group name="4b74769ab7c143c2b8616e89c0d44673fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="Plane003" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane004" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane005" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <group name="Roadmap001" rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
          <group name="4b74769ab7c143c2b8616e89c0d44673fbx001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode001">
              <group name="Plane124" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane125" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane126" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <group name="Roadmap002" rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
          <group name="4b74769ab7c143c2b8616e89c0d44673fbx002" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode002">
              <group name="Plane127" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane128" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane129" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <group name="Roadmap003" rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
          <group name="4b74769ab7c143c2b8616e89c0d44673fbx003" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode003">
              <group name="Plane130" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane131" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane132" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <group name="Roadmap005" rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
          <group name="4b74769ab7c143c2b8616e89c0d44673fbx005" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode005">
              <group name="Plane136" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane137" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane138" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <group name="Roadmap006" rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
          <group name="4b74769ab7c143c2b8616e89c0d44673fbx006" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode006">
              <group name="Plane139" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane140" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane141" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <group name="Roadmap007" rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
          <group name="4b74769ab7c143c2b8616e89c0d44673fbx007" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode007">
              <group name="Plane142" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane143" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="Plane144" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <mesh name="Rooftop_vent_01010" geometry={nodes.Rooftop_vent_01010.geometry} material={materials['Material.016']} position={[-0.032, 4.666, -1.315]} scale={0.116} />
        <mesh name="Rooftop_vent_01009" geometry={nodes.Rooftop_vent_01009.geometry} material={materials['Material.016']} position={[-0.032, 4.666, -2.336]} scale={0.116} />
        <mesh name="Rooftop_vent_01008" geometry={nodes.Rooftop_vent_01008.geometry} material={materials['Material.016']} position={[0.545, 4.666, -2.724]} scale={0.116} />
        <mesh name="Rooftop_vent_01007" geometry={nodes.Rooftop_vent_01007.geometry} material={materials['Material.016']} position={[-0.032, 4.666, -2.724]} scale={0.116} />
        <mesh name="Rooftop_vent_01006" geometry={nodes.Rooftop_vent_01006.geometry} material={materials['Material.016']} position={[-0.565, 4.666, -2.724]} scale={0.116} />
        <mesh name="Rooftop_vent_01005" geometry={nodes.Rooftop_vent_01005.geometry} material={materials['Material.016']} position={[0.545, 4.666, -1.896]} scale={0.116} />
        <mesh name="Rooftop_vent_01004" geometry={nodes.Rooftop_vent_01004.geometry} material={materials['Material.016']} position={[-0.032, 4.666, -1.896]} scale={0.116} />
        <mesh name="Rooftop_vent_01003" geometry={nodes.Rooftop_vent_01003.geometry} material={materials['Material.016']} position={[-0.565, 4.666, -1.896]} scale={0.116} />
        <mesh name="Rooftop_vent_01002" geometry={nodes.Rooftop_vent_01002.geometry} material={materials['Material.016']} position={[0.545, 4.666, -0.748]} scale={0.116} />
        <mesh name="Rooftop_vent_01001" geometry={nodes.Rooftop_vent_01001.geometry} material={materials['Material.016']} position={[-0.032, 4.666, -0.748]} scale={0.116} />
        <mesh name="Rooftop_vent_01" geometry={nodes.Rooftop_vent_01.geometry} material={materials['Material.016']} position={[-0.565, 4.666, -0.748]} scale={0.116} />
        <mesh name="Plane072" geometry={nodes.Plane072.geometry} material={nodes.Plane072.material} position={[-1.409, 3.138, -0.181]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.181, 1, 1.91]} />
        <mesh name="Plane071" geometry={nodes.Plane071.geometry} material={nodes.Plane071.material} position={[-1.409, 3.138, -3.197]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.181, 1, 1.91]} />
        <mesh name="Plane070" geometry={nodes.Plane070.geometry} material={nodes.Plane070.material} position={[1.361, 3.138, -3.197]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.181, 1, 1.91]} />
        <mesh name="Plane069" geometry={nodes.Plane069.geometry} material={nodes.Plane069.material} position={[1.361, 3.138, -0.161]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.181, 1, 1.91]} />
        <mesh name="Plane068" geometry={nodes.Plane068.geometry} material={nodes.Plane068.material} position={[-0.025, 4.661, -1.675]} scale={[1.043, 1, 1.411]} />
        <mesh name="Plane067" geometry={nodes.Plane067.geometry} material={materials.galss} position={[-0.039, 0.038, -3.371]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Plane066" geometry={nodes.Plane066.geometry} material={materials.Glass} position={[-0.039, 0.038, -3.371]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Plane065" geometry={nodes.Plane065.geometry} material={nodes.Plane065.material} position={[-0.039, 0.038, -3.371]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Plane064" geometry={nodes.Plane064.geometry} material={nodes.Plane064.material} position={[-0.039, 0.038, -3.371]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Plane063" geometry={nodes.Plane063.geometry} material={nodes.Plane063.material} position={[-0.039, 0.038, -3.371]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Plane053" geometry={nodes.Plane053.geometry} material={materials['Material.001']} position={[-0.039, 0.038, -3.371]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Plane052" geometry={nodes.Plane052.geometry} material={materials['Material.002']} position={[-0.039, 0.038, -3.371]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Plane051" geometry={nodes.Plane051.geometry} material={materials['Material.001']} position={[-0.039, 0.038, -3.371]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Plane050" geometry={nodes.Plane050.geometry} material={materials.galss} position={[-1.388, 0.038, -1.658]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane049" geometry={nodes.Plane049.geometry} material={materials.window} position={[-1.388, 0.038, -1.658]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane048" geometry={nodes.Plane048.geometry} material={nodes.Plane048.material} position={[-1.388, 0.038, -1.658]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane047" geometry={nodes.Plane047.geometry} material={nodes.Plane047.material} position={[-1.388, 0.038, -1.658]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane046" geometry={nodes.Plane046.geometry} material={nodes.Plane046.material} position={[-1.388, 0.038, -1.658]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane036" geometry={nodes.Plane036.geometry} material={materials['Material.001']} position={[-1.388, 0.038, -1.658]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane035" geometry={nodes.Plane035.geometry} material={materials['Material.002']} position={[-1.388, 0.038, -1.658]} rotation={[0, -Math.PI / 2, 0]} />
        <group name="Plane034" position={[-1.388, 0.025, -1.658]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh name="Plane035_1" geometry={nodes.Plane035_1.geometry} material={materials['Material.001']} />
          <mesh name="Plane035_2" geometry={nodes.Plane035_2.geometry} material={materials.window} />
        </group>
        <mesh name="Plane033" geometry={nodes.Plane033.geometry} material={materials.galss} position={[1.597, 0.038, -1.697]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Plane032" geometry={nodes.Plane032.geometry} material={materials.window} position={[1.433, 0.038, -1.697]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Plane031" geometry={nodes.Plane031.geometry} material={nodes.Plane031.material} position={[1.334, 0.038, -1.697]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Plane030" geometry={nodes.Plane030.geometry} material={nodes.Plane030.material} position={[1.334, 0.038, -1.697]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={nodes.Plane029.material} position={[1.334, 0.038, -1.697]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials['Material.001']} position={[1.334, 0.038, -1.697]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['Material.002']} position={[1.597, 0.038, -1.697]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials.window} position={[1.356, 0.03, -1.697]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials.galss} position={[0, 0.038, 0.227]} />
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials.galss} position={[0, 0.038, 0]} />
        <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} position={[0, 0.038, 0]} />
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={nodes.Plane013.material} position={[0, 0.038, 0]} />
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={nodes.Plane012.material} position={[0, 0.038, 0]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.001']} position={[0, 0.038, 0]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.002']} position={[0, 0.038, 0.227]} />
        <group name="Plane" position={[0, 0.038, 0]}>
          <mesh name="Plane002_1" geometry={nodes.Plane002_1.geometry} material={materials['Material.001']} />
          <mesh name="Plane002_2" geometry={nodes.Plane002_2.geometry} material={materials['Material.003']} />
        </group>
        <group name="Cube001" position={[-0.021, 0.67, -1.689]} scale={[1.455, 0.627, 1.742]}>
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials['Material.004']} />
          <mesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.black} />
          <mesh name="Cube001_3" geometry={nodes.Cube001_3.geometry} material={materials['Material.006']} />
          <mesh name="Cube001_4" geometry={nodes.Cube001_4.geometry} material={materials['Material.012']} />
          <mesh name="Cube001_5" geometry={nodes.Cube001_5.geometry} material={materials['Material.013']} />
          <mesh name="Cube001_6" geometry={nodes.Cube001_6.geometry} material={materials['Material.014']} />
          <mesh name="Cube001_7" geometry={nodes.Cube001_7.geometry} material={materials['Material.015']} />
          <mesh name="Cube001_8" geometry={nodes.Cube001_8.geometry} material={materials['Material.017']} />
          <mesh name="Cube001_9" geometry={nodes.Cube001_9.geometry} material={materials['Material.018']} />
          <mesh name="Cube001_10" geometry={nodes.Cube001_10.geometry} material={nodes.Cube001_10.material} />
        </group>
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.black} position={[-0.021, 0.555, -1.689]} scale={[1.455, 0.627, 1.742]} />
        <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials['Material.003']} position={[-0.029, 2.959, -1.75]} rotation={[Math.PI / 2, 0, 0]} scale={[1.051, 1, 1.643]} />
        <mesh name="Plane026" geometry={nodes.Plane026.geometry} material={materials['Material.003']} position={[-0.029, 2.959, -2.342]} rotation={[Math.PI / 2, 0, 0]} scale={[1.051, 1, 1.643]} />
        <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials['Material.003']} position={[-0.029, 2.959, -1.252]} rotation={[Math.PI / 2, 0, 0]} scale={[1.051, 1, 1.643]} />
        <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={materials['Material.005']} position={[0, 2.959, -1.692]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.389, 1, 1.643]} />
        <mesh name="Plane024" geometry={nodes.Plane024.geometry} material={materials['Material.005']} position={[0.522, 2.959, -1.692]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.389, 1, 1.643]} />
        <mesh name="Plane025" geometry={nodes.Plane025.geometry} material={materials['Material.005']} position={[-0.533, 2.959, -1.692]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.389, 1, 1.643]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[0, 0.908, -1.488]} scale={[2.024, 0.03, 0.721]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.black} position={[1.565, 4.242, -1.914]} scale={[1.172, 0.627, 1.742]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.007']} position={[-0.494, 4.719, -0.338]} scale={[0.88, 0.02, 0.045]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[-1.128, 4.461, -0.015]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[-1.128, 4.153, -0.015]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[-1.128, 3.835, -0.015]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[-1.128, 3.523, -0.015]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[-1.128, 3.221, -0.015]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[-1.128, 2.904, -0.015]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[-1.128, 2.59, -0.015]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[-1.128, 2.275, -0.015]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[-1.128, 1.965, -0.015]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[-1.128, 1.654, -0.015]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[-1.128, 1.399, -0.015]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[-0.097, 4.461, -0.015]} scale={[0.206, 0.007, 0.01]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[-0.097, 4.152, -0.015]} scale={[0.201, 0.007, 0.01]} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[-0.096, 3.837, -0.015]} scale={[0.201, 0.007, 0.01]} />
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} position={[-0.095, 3.522, -0.015]} scale={[0.2, 0.007, 0.01]} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} position={[-0.095, 3.22, -0.015]} scale={[0.204, 0.007, 0.01]} />
        <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} position={[-0.096, 2.906, -0.015]} scale={[0.206, 0.007, 0.01]} />
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} position={[-0.094, 2.591, -0.015]} scale={[0.203, 0.007, 0.01]} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={nodes.Cube023.material} position={[-0.096, 2.276, -0.015]} scale={[0.203, 0.007, 0.01]} />
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={nodes.Cube024.material} position={[-0.094, 1.965, -0.015]} scale={[0.204, 0.007, 0.01]} />
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={nodes.Cube025.material} position={[-0.097, 1.656, -0.015]} scale={[0.208, 0.007, 0.01]} />
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={nodes.Cube026.material} position={[-0.096, 1.399, -0.015]} scale={[0.205, 0.007, 0.01]} />
        <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={nodes.Cube027.material} position={[1.015, 4.464, -0.015]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={nodes.Cube028.material} position={[1.015, 4.155, -0.015]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube029" geometry={nodes.Cube029.geometry} material={nodes.Cube029.material} position={[1.015, 3.839, -0.015]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube030" geometry={nodes.Cube030.geometry} material={nodes.Cube030.material} position={[1.015, 3.526, -0.015]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube031" geometry={nodes.Cube031.geometry} material={nodes.Cube031.material} position={[1.015, 3.221, -0.015]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube032" geometry={nodes.Cube032.geometry} material={nodes.Cube032.material} position={[1.015, 2.907, -0.015]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube033" geometry={nodes.Cube033.geometry} material={nodes.Cube033.material} position={[1.015, 2.594, -0.015]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={nodes.Cube034.material} position={[1.015, 2.276, -0.015]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={nodes.Cube035.material} position={[1.015, 1.97, -0.015]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={nodes.Cube036.material} position={[1.015, 1.657, -0.015]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube037" geometry={nodes.Cube037.geometry} material={nodes.Cube037.material} position={[1.015, 1.399, -0.015]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={nodes.Cube038.material} position={[0.389, 4.461, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube039" geometry={nodes.Cube039.geometry} material={nodes.Cube039.material} position={[0.389, 4.152, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={nodes.Cube040.material} position={[0.389, 3.838, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube041" geometry={nodes.Cube041.geometry} material={nodes.Cube041.material} position={[0.389, 3.524, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube042" geometry={nodes.Cube042.geometry} material={nodes.Cube042.material} position={[0.389, 3.219, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube043" geometry={nodes.Cube043.geometry} material={nodes.Cube043.material} position={[0.389, 2.905, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube044" geometry={nodes.Cube044.geometry} material={nodes.Cube044.material} position={[0.389, 2.589, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube045" geometry={nodes.Cube045.geometry} material={nodes.Cube045.material} position={[0.389, 2.274, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube046" geometry={nodes.Cube046.geometry} material={nodes.Cube046.material} position={[0.389, 1.964, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube047" geometry={nodes.Cube047.geometry} material={nodes.Cube047.material} position={[0.389, 1.654, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube048" geometry={nodes.Cube048.geometry} material={nodes.Cube048.material} position={[0.389, 1.399, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube049" geometry={nodes.Cube049.geometry} material={nodes.Cube049.material} position={[-0.587, 4.463, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube050" geometry={nodes.Cube050.geometry} material={nodes.Cube050.material} position={[-0.587, 4.156, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube051" geometry={nodes.Cube051.geometry} material={nodes.Cube051.material} position={[-0.587, 3.84, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube052" geometry={nodes.Cube052.geometry} material={nodes.Cube052.material} position={[-0.587, 3.526, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube053" geometry={nodes.Cube053.geometry} material={nodes.Cube053.material} position={[-0.587, 3.221, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube054" geometry={nodes.Cube054.geometry} material={nodes.Cube054.material} position={[-0.587, 2.907, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube055" geometry={nodes.Cube055.geometry} material={nodes.Cube055.material} position={[-0.587, 2.592, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube056" geometry={nodes.Cube056.geometry} material={nodes.Cube056.material} position={[-0.587, 2.276, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube057" geometry={nodes.Cube057.geometry} material={nodes.Cube057.material} position={[-0.587, 1.967, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube058" geometry={nodes.Cube058.geometry} material={nodes.Cube058.material} position={[-0.587, 1.656, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube059" geometry={nodes.Cube059.geometry} material={nodes.Cube059.material} position={[-0.587, 1.399, -0.139]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube060" geometry={nodes.Cube060.geometry} material={materials['Material.007']} position={[-1.175, 4.702, -2.119]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={[0.88, 0.02, 0.045]} />
        <mesh name="Cube061" geometry={nodes.Cube061.geometry} material={materials['Concrete tiles']} position={[-0.387, 0.011, -0.997]} scale={[2.576, 0.048, 2.629]} />
        <mesh name="Plane045" geometry={nodes.Plane045.geometry} material={materials.galss} position={[-1.388, 4.4, -0.659]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane054" geometry={nodes.Plane054.geometry} material={materials.galss} position={[-1.382, 4.089, -0.659]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane055" geometry={nodes.Plane055.geometry} material={materials.galss} position={[-1.385, 3.773, -0.659]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane056" geometry={nodes.Plane056.geometry} material={materials.galss} position={[-1.382, 3.453, -0.659]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane057" geometry={nodes.Plane057.geometry} material={materials.galss} position={[-1.389, 3.157, -0.659]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane058" geometry={nodes.Plane058.geometry} material={materials.galss} position={[-1.378, 2.835, -0.659]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane059" geometry={nodes.Plane059.geometry} material={materials.galss} position={[-1.377, 2.526, -0.659]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane060" geometry={nodes.Plane060.geometry} material={materials.galss} position={[-1.368, 2.207, -0.659]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane061" geometry={nodes.Plane061.geometry} material={materials.galss} position={[-1.368, 1.889, -0.659]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane062" geometry={nodes.Plane062.geometry} material={materials.galss} position={[-1.368, 1.583, -0.659]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane073" geometry={nodes.Plane073.geometry} material={materials.galss} position={[-1.368, 1.364, -0.659]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane074" geometry={nodes.Plane074.geometry} material={materials.galss} position={[-1.385, 4.4, -2.784]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.078, 1, 1]} />
        <mesh name="Plane075" geometry={nodes.Plane075.geometry} material={materials.galss} position={[-1.385, 4.095, -2.784]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.078, 1, 1]} />
        <mesh name="Plane076" geometry={nodes.Plane076.geometry} material={materials.galss} position={[-1.383, 3.772, -2.784]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.078, 1, 1]} />
        <mesh name="Plane077" geometry={nodes.Plane077.geometry} material={materials.galss} position={[-1.384, 3.46, -2.784]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.078, 1, 1]} />
        <mesh name="Plane078" geometry={nodes.Plane078.geometry} material={materials.galss} position={[-1.384, 3.152, -2.784]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.078, 1, 1]} />
        <mesh name="Plane079" geometry={nodes.Plane079.geometry} material={materials.galss} position={[-1.384, 2.833, -2.784]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.078, 1, 1]} />
        <mesh name="Plane080" geometry={nodes.Plane080.geometry} material={materials.galss} position={[-1.384, 2.524, -2.784]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.078, 1, 1]} />
        <mesh name="Plane081" geometry={nodes.Plane081.geometry} material={materials.galss} position={[-1.384, 2.207, -2.784]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.078, 1, 1]} />
        <mesh name="Plane082" geometry={nodes.Plane082.geometry} material={materials.galss} position={[-1.384, 1.893, -2.784]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.078, 1, 1]} />
        <mesh name="Plane083" geometry={nodes.Plane083.geometry} material={materials.galss} position={[-1.384, 1.586, -2.784]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.078, 1, 1]} />
        <mesh name="Plane084" geometry={nodes.Plane084.geometry} material={materials.galss} position={[-1.384, 1.369, -2.784]} rotation={[Math.PI, -1.559, Math.PI]} scale={[1.078, 1, 1]} />
        <mesh name="Plane085" geometry={nodes.Plane085.geometry} material={materials.galss} position={[-1.372, 4.396, -1.763]} rotation={[Math.PI, -1.559, Math.PI]} scale={[0.848, 1, 1]} />
        <mesh name="Plane086" geometry={nodes.Plane086.geometry} material={materials.galss} position={[-1.372, 4.085, -1.763]} rotation={[Math.PI, -1.559, Math.PI]} scale={[0.848, 1, 1]} />
        <mesh name="Plane087" geometry={nodes.Plane087.geometry} material={materials.galss} position={[-1.372, 3.773, -1.763]} rotation={[Math.PI, -1.559, Math.PI]} scale={[0.848, 1, 1]} />
        <mesh name="Plane088" geometry={nodes.Plane088.geometry} material={materials.galss} position={[-1.372, 3.457, -1.763]} rotation={[Math.PI, -1.559, Math.PI]} scale={[0.848, 1, 1]} />
        <mesh name="Plane089" geometry={nodes.Plane089.geometry} material={materials.galss} position={[-1.372, 3.151, -1.763]} rotation={[Math.PI, -1.559, Math.PI]} scale={[0.848, 1, 1]} />
        <mesh name="Plane090" geometry={nodes.Plane090.geometry} material={materials.galss} position={[-1.372, 2.841, -1.763]} rotation={[Math.PI, -1.559, Math.PI]} scale={[0.848, 1, 1]} />
        <mesh name="Plane091" geometry={nodes.Plane091.geometry} material={materials.galss} position={[-1.372, 2.526, -1.763]} rotation={[Math.PI, -1.559, Math.PI]} scale={[0.848, 1, 1]} />
        <mesh name="Plane092" geometry={nodes.Plane092.geometry} material={materials.galss} position={[-1.372, 2.21, -1.763]} rotation={[Math.PI, -1.559, Math.PI]} scale={[0.848, 1, 1]} />
        <mesh name="Plane093" geometry={nodes.Plane093.geometry} material={materials.galss} position={[-1.372, 1.893, -1.763]} rotation={[Math.PI, -1.559, Math.PI]} scale={[0.848, 1, 1]} />
        <mesh name="Plane094" geometry={nodes.Plane094.geometry} material={materials.galss} position={[-1.372, 1.583, -1.763]} rotation={[Math.PI, -1.559, Math.PI]} scale={[0.848, 1, 1]} />
        <mesh name="Plane095" geometry={nodes.Plane095.geometry} material={materials.galss} position={[-1.381, 1.369, -1.763]} rotation={[Math.PI, -1.559, Math.PI]} scale={[0.848, 1, 1]} />
        <mesh name="Cube062" geometry={nodes.Cube062.geometry} material={nodes.Cube062.material} position={[-1.401, 0.19, 0.289]} scale={[0.038, 0.137, 0.31]} />
        <mesh name="Cube063" geometry={nodes.Cube063.geometry} material={nodes.Cube063.material} position={[1.361, 0.19, 0.289]} scale={[0.038, 0.137, 0.31]} />
        <mesh name="Cube066" geometry={nodes.Cube066.geometry} material={nodes.Cube066.material} position={[-2.24, 0.19, 0.289]} scale={[0.038, 0.137, 0.31]} />
        <mesh name="Cube065" geometry={nodes.Cube065.geometry} material={nodes.Cube065.material} position={[2.246, 0.19, 0.289]} scale={[0.038, 0.137, 0.31]} />
        <mesh name="Cube064" geometry={nodes.Cube064.geometry} material={nodes.Cube064.material} position={[-0.029, 0.042, 0.097]} scale={[1.338, 0.034, 0.859]} />
        <mesh name="Cube067" geometry={nodes.Cube067.geometry} material={nodes.Cube067.material} position={[-0.029, 0.042, 0]} scale={[1.338, 0.034, 0.859]} />
        <mesh name="Cube068" geometry={nodes.Cube068.geometry} material={materials['Grey tiles']} position={[-0.029, 0.074, 0.057]} scale={[1.338, 0.02, 0.859]} />
        <mesh name="Cube071" geometry={nodes.Cube071.geometry} material={materials['Material.020']} position={[0, 0.908, -1.488]} scale={[2.024, 0.03, 0.721]} />
        <mesh name="Cube072" geometry={nodes.Cube072.geometry} material={materials['Material.007']} position={[-1.078, 4.702, -2.119]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={[0.88, 0.02, 0.045]} />
        <mesh name="Cube073" geometry={nodes.Cube073.geometry} material={materials['Material.007']} position={[1.172, 4.702, -1.216]} rotation={[-Math.PI, 1.569, -Math.PI]} scale={[0.88, 0.02, 0.045]} />
        <mesh name="Cube074" geometry={nodes.Cube074.geometry} material={materials['Material.007']} position={[0.45, 4.719, -3.185]} scale={[0.88, 0.02, 0.045]} />
        <mesh name="Cube075" geometry={nodes.Cube075.geometry} material={nodes.Cube075.material} position={[1.088, 4.461, -3.34]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube076" geometry={nodes.Cube076.geometry} material={nodes.Cube076.material} position={[1.088, 4.153, -3.34]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube077" geometry={nodes.Cube077.geometry} material={nodes.Cube077.material} position={[1.088, 3.835, -3.34]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube078" geometry={nodes.Cube078.geometry} material={nodes.Cube078.material} position={[1.088, 3.523, -3.34]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube079" geometry={nodes.Cube079.geometry} material={nodes.Cube079.material} position={[1.088, 3.221, -3.34]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube080" geometry={nodes.Cube080.geometry} material={nodes.Cube080.material} position={[1.088, 2.904, -3.34]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube081" geometry={nodes.Cube081.geometry} material={nodes.Cube081.material} position={[1.088, 2.59, -3.34]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube082" geometry={nodes.Cube082.geometry} material={nodes.Cube082.material} position={[1.088, 2.275, -3.34]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube083" geometry={nodes.Cube083.geometry} material={nodes.Cube083.material} position={[1.088, 1.965, -3.34]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube084" geometry={nodes.Cube084.geometry} material={nodes.Cube084.material} position={[1.088, 1.654, -3.34]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube085" geometry={nodes.Cube085.geometry} material={nodes.Cube085.material} position={[1.088, 1.399, -3.34]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube086" geometry={nodes.Cube086.geometry} material={nodes.Cube086.material} position={[0.057, 4.461, -3.342]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.206, 0.007, 0.01]} />
        <mesh name="Cube087" geometry={nodes.Cube087.geometry} material={nodes.Cube087.material} position={[0.057, 4.152, -3.342]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.201, 0.007, 0.01]} />
        <mesh name="Cube088" geometry={nodes.Cube088.geometry} material={nodes.Cube088.material} position={[0.056, 3.837, -3.342]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.201, 0.007, 0.01]} />
        <mesh name="Cube089" geometry={nodes.Cube089.geometry} material={nodes.Cube089.material} position={[0.055, 3.522, -3.342]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.2, 0.007, 0.01]} />
        <mesh name="Cube090" geometry={nodes.Cube090.geometry} material={nodes.Cube090.material} position={[0.055, 3.22, -3.342]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.204, 0.007, 0.01]} />
        <mesh name="Cube091" geometry={nodes.Cube091.geometry} material={nodes.Cube091.material} position={[0.056, 2.906, -3.342]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.206, 0.007, 0.01]} />
        <mesh name="Cube092" geometry={nodes.Cube092.geometry} material={nodes.Cube092.material} position={[0.054, 2.591, -3.342]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.203, 0.007, 0.01]} />
        <mesh name="Cube093" geometry={nodes.Cube093.geometry} material={nodes.Cube093.material} position={[0.056, 2.276, -3.342]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.203, 0.007, 0.01]} />
        <mesh name="Cube094" geometry={nodes.Cube094.geometry} material={nodes.Cube094.material} position={[0.054, 1.965, -3.342]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.204, 0.007, 0.01]} />
        <mesh name="Cube095" geometry={nodes.Cube095.geometry} material={nodes.Cube095.material} position={[0.057, 1.656, -3.342]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.208, 0.007, 0.01]} />
        <mesh name="Cube096" geometry={nodes.Cube096.geometry} material={nodes.Cube096.material} position={[0.056, 1.399, -3.342]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.205, 0.007, 0.01]} />
        <mesh name="Cube097" geometry={nodes.Cube097.geometry} material={nodes.Cube097.material} position={[-1.056, 4.464, -3.344]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube098" geometry={nodes.Cube098.geometry} material={nodes.Cube098.material} position={[-1.056, 4.155, -3.344]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube099" geometry={nodes.Cube099.geometry} material={nodes.Cube099.material} position={[-1.056, 3.839, -3.344]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube100" geometry={nodes.Cube100.geometry} material={nodes.Cube100.material} position={[-1.056, 3.526, -3.344]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube101" geometry={nodes.Cube101.geometry} material={nodes.Cube101.material} position={[-1.056, 3.221, -3.344]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube102" geometry={nodes.Cube102.geometry} material={nodes.Cube102.material} position={[-1.056, 2.907, -3.344]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube103" geometry={nodes.Cube103.geometry} material={nodes.Cube103.material} position={[-1.056, 2.594, -3.344]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube104" geometry={nodes.Cube104.geometry} material={nodes.Cube104.material} position={[-1.056, 2.276, -3.344]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube105" geometry={nodes.Cube105.geometry} material={nodes.Cube105.material} position={[-1.056, 1.97, -3.344]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube106" geometry={nodes.Cube106.geometry} material={nodes.Cube106.material} position={[-1.056, 1.657, -3.344]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube107" geometry={nodes.Cube107.geometry} material={nodes.Cube107.material} position={[-1.056, 1.399, -3.344]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube108" geometry={nodes.Cube108.geometry} material={nodes.Cube108.material} position={[0.536, 4.461, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube109" geometry={nodes.Cube109.geometry} material={nodes.Cube109.material} position={[0.536, 4.152, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube110" geometry={nodes.Cube110.geometry} material={nodes.Cube110.material} position={[0.536, 3.838, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube111" geometry={nodes.Cube111.geometry} material={nodes.Cube111.material} position={[0.536, 3.524, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube112" geometry={nodes.Cube112.geometry} material={nodes.Cube112.material} position={[0.536, 3.219, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube113" geometry={nodes.Cube113.geometry} material={nodes.Cube113.material} position={[0.536, 2.905, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube114" geometry={nodes.Cube114.geometry} material={nodes.Cube114.material} position={[0.536, 2.589, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube115" geometry={nodes.Cube115.geometry} material={nodes.Cube115.material} position={[0.536, 2.274, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube116" geometry={nodes.Cube116.geometry} material={nodes.Cube116.material} position={[0.536, 1.964, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube117" geometry={nodes.Cube117.geometry} material={nodes.Cube117.material} position={[0.536, 1.654, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube118" geometry={nodes.Cube118.geometry} material={nodes.Cube118.material} position={[0.536, 1.399, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube119" geometry={nodes.Cube119.geometry} material={nodes.Cube119.material} position={[-0.44, 4.463, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube120" geometry={nodes.Cube120.geometry} material={nodes.Cube120.material} position={[-0.44, 4.156, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube121" geometry={nodes.Cube121.geometry} material={nodes.Cube121.material} position={[-0.44, 3.84, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube122" geometry={nodes.Cube122.geometry} material={nodes.Cube122.material} position={[-0.44, 3.526, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube123" geometry={nodes.Cube123.geometry} material={nodes.Cube123.material} position={[-0.44, 3.221, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube124" geometry={nodes.Cube124.geometry} material={nodes.Cube124.material} position={[-0.44, 2.907, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube125" geometry={nodes.Cube125.geometry} material={nodes.Cube125.material} position={[-0.44, 2.592, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube126" geometry={nodes.Cube126.geometry} material={nodes.Cube126.material} position={[-0.44, 2.276, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube127" geometry={nodes.Cube127.geometry} material={nodes.Cube127.material} position={[-0.44, 1.967, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube128" geometry={nodes.Cube128.geometry} material={nodes.Cube128.material} position={[-0.44, 1.656, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube129" geometry={nodes.Cube129.geometry} material={nodes.Cube129.material} position={[-0.44, 1.399, -3.221]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials.galss} position={[1.343, 4.4, -2.704]} rotation={[0, 1.563, 0]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials.galss} position={[1.337, 4.089, -2.704]} rotation={[0, 1.563, 0]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials.galss} position={[1.341, 3.773, -2.704]} rotation={[0, 1.563, 0]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={materials.galss} position={[1.337, 3.453, -2.704]} rotation={[0, 1.563, 0]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={materials.galss} position={[1.345, 3.157, -2.704]} rotation={[0, 1.563, 0]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane096" geometry={nodes.Plane096.geometry} material={materials.galss} position={[1.333, 2.835, -2.704]} rotation={[0, 1.563, 0]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane097" geometry={nodes.Plane097.geometry} material={materials.galss} position={[1.333, 2.526, -2.704]} rotation={[0, 1.563, 0]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane098" geometry={nodes.Plane098.geometry} material={materials.galss} position={[1.323, 2.207, -2.704]} rotation={[0, 1.563, 0]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane099" geometry={nodes.Plane099.geometry} material={materials.galss} position={[1.323, 1.889, -2.704]} rotation={[0, 1.563, 0]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane100" geometry={nodes.Plane100.geometry} material={materials.galss} position={[1.323, 1.583, -2.704]} rotation={[0, 1.563, 0]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane101" geometry={nodes.Plane101.geometry} material={materials.galss} position={[1.323, 1.364, -2.704]} rotation={[0, 1.563, 0]} scale={[1.347, 1, 1.001]} />
        <mesh name="Plane102" geometry={nodes.Plane102.geometry} material={materials.galss} position={[1.348, 4.4, -0.579]} rotation={[0, 1.563, 0]} scale={[1.078, 1, 1]} />
        <mesh name="Plane103" geometry={nodes.Plane103.geometry} material={materials.galss} position={[1.348, 4.095, -0.579]} rotation={[0, 1.563, 0]} scale={[1.078, 1, 1]} />
        <mesh name="Plane104" geometry={nodes.Plane104.geometry} material={materials.galss} position={[1.346, 3.772, -0.579]} rotation={[0, 1.563, 0]} scale={[1.078, 1, 1]} />
        <mesh name="Plane105" geometry={nodes.Plane105.geometry} material={materials.galss} position={[1.347, 3.46, -0.579]} rotation={[0, 1.563, 0]} scale={[1.078, 1, 1]} />
        <mesh name="Plane106" geometry={nodes.Plane106.geometry} material={materials.galss} position={[1.347, 3.152, -0.579]} rotation={[0, 1.563, 0]} scale={[1.078, 1, 1]} />
        <mesh name="Plane107" geometry={nodes.Plane107.geometry} material={materials.galss} position={[1.347, 2.833, -0.579]} rotation={[0, 1.563, 0]} scale={[1.078, 1, 1]} />
        <mesh name="Plane108" geometry={nodes.Plane108.geometry} material={materials.galss} position={[1.347, 2.524, -0.579]} rotation={[0, 1.563, 0]} scale={[1.078, 1, 1]} />
        <mesh name="Plane109" geometry={nodes.Plane109.geometry} material={materials.galss} position={[1.347, 2.207, -0.579]} rotation={[0, 1.563, 0]} scale={[1.078, 1, 1]} />
        <mesh name="Plane110" geometry={nodes.Plane110.geometry} material={materials.galss} position={[1.347, 1.893, -0.579]} rotation={[0, 1.563, 0]} scale={[1.078, 1, 1]} />
        <mesh name="Plane111" geometry={nodes.Plane111.geometry} material={materials.galss} position={[1.347, 1.586, -0.579]} rotation={[0, 1.563, 0]} scale={[1.078, 1, 1]} />
        <mesh name="Plane112" geometry={nodes.Plane112.geometry} material={materials.galss} position={[1.347, 1.369, -0.579]} rotation={[0, 1.563, 0]} scale={[1.078, 1, 1]} />
        <mesh name="Plane113" geometry={nodes.Plane113.geometry} material={materials.galss} position={[1.332, 4.396, -1.6]} rotation={[0, 1.563, 0]} scale={[0.848, 1, 1]} />
        <mesh name="Plane114" geometry={nodes.Plane114.geometry} material={materials.galss} position={[1.332, 4.085, -1.6]} rotation={[0, 1.563, 0]} scale={[0.848, 1, 1]} />
        <mesh name="Plane115" geometry={nodes.Plane115.geometry} material={materials.galss} position={[1.332, 3.773, -1.6]} rotation={[0, 1.563, 0]} scale={[0.848, 1, 1]} />
        <mesh name="Plane116" geometry={nodes.Plane116.geometry} material={materials.galss} position={[1.332, 3.457, -1.6]} rotation={[0, 1.563, 0]} scale={[0.848, 1, 1]} />
        <mesh name="Plane117" geometry={nodes.Plane117.geometry} material={materials.galss} position={[1.332, 3.151, -1.6]} rotation={[0, 1.563, 0]} scale={[0.848, 1, 1]} />
        <mesh name="Plane118" geometry={nodes.Plane118.geometry} material={materials.galss} position={[1.332, 2.841, -1.6]} rotation={[0, 1.563, 0]} scale={[0.848, 1, 1]} />
        <mesh name="Plane119" geometry={nodes.Plane119.geometry} material={materials.galss} position={[1.332, 2.526, -1.6]} rotation={[0, 1.563, 0]} scale={[0.848, 1, 1]} />
        <mesh name="Plane120" geometry={nodes.Plane120.geometry} material={materials.galss} position={[1.332, 2.21, -1.6]} rotation={[0, 1.563, 0]} scale={[0.848, 1, 1]} />
        <mesh name="Plane121" geometry={nodes.Plane121.geometry} material={materials.galss} position={[1.332, 1.893, -1.6]} rotation={[0, 1.563, 0]} scale={[0.848, 1, 1]} />
        <mesh name="Plane122" geometry={nodes.Plane122.geometry} material={materials.galss} position={[1.332, 1.583, -1.6]} rotation={[0, 1.563, 0]} scale={[0.848, 1, 1]} />
        <mesh name="Plane123" geometry={nodes.Plane123.geometry} material={materials.galss} position={[1.341, 1.369, -1.6]} rotation={[0, 1.563, 0]} scale={[0.848, 1, 1]} />
        <mesh name="Cube130" geometry={nodes.Cube130.geometry} material={nodes.Cube130.material} position={[1.326, 4.461, -0.557]} rotation={[0, 1.561, 0]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube131" geometry={nodes.Cube131.geometry} material={nodes.Cube131.material} position={[1.326, 4.153, -0.557]} rotation={[0, 1.561, 0]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube132" geometry={nodes.Cube132.geometry} material={nodes.Cube132.material} position={[1.326, 3.835, -0.557]} rotation={[0, 1.561, 0]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube133" geometry={nodes.Cube133.geometry} material={nodes.Cube133.material} position={[1.326, 3.523, -0.557]} rotation={[0, 1.561, 0]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube134" geometry={nodes.Cube134.geometry} material={nodes.Cube134.material} position={[1.326, 3.221, -0.557]} rotation={[0, 1.561, 0]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube135" geometry={nodes.Cube135.geometry} material={nodes.Cube135.material} position={[1.326, 2.904, -0.557]} rotation={[0, 1.561, 0]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube136" geometry={nodes.Cube136.geometry} material={nodes.Cube136.material} position={[1.326, 2.59, -0.557]} rotation={[0, 1.561, 0]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube137" geometry={nodes.Cube137.geometry} material={nodes.Cube137.material} position={[1.326, 2.275, -0.557]} rotation={[0, 1.561, 0]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube138" geometry={nodes.Cube138.geometry} material={nodes.Cube138.material} position={[1.326, 1.965, -0.557]} rotation={[0, 1.561, 0]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube139" geometry={nodes.Cube139.geometry} material={nodes.Cube139.material} position={[1.326, 1.654, -0.557]} rotation={[0, 1.561, 0]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube140" geometry={nodes.Cube140.geometry} material={nodes.Cube140.material} position={[1.326, 1.399, -0.557]} rotation={[0, 1.561, 0]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube141" geometry={nodes.Cube141.geometry} material={nodes.Cube141.material} position={[1.336, 4.461, -1.587]} rotation={[0, 1.561, 0]} scale={[0.206, 0.007, 0.01]} />
        <mesh name="Cube142" geometry={nodes.Cube142.geometry} material={nodes.Cube142.material} position={[1.336, 4.152, -1.588]} rotation={[0, 1.561, 0]} scale={[0.201, 0.007, 0.01]} />
        <mesh name="Cube143" geometry={nodes.Cube143.geometry} material={nodes.Cube143.material} position={[1.336, 3.837, -1.589]} rotation={[0, 1.561, 0]} scale={[0.201, 0.007, 0.01]} />
        <mesh name="Cube144" geometry={nodes.Cube144.geometry} material={nodes.Cube144.material} position={[1.336, 3.522, -1.589]} rotation={[0, 1.561, 0]} scale={[0.2, 0.007, 0.01]} />
        <mesh name="Cube145" geometry={nodes.Cube145.geometry} material={nodes.Cube145.material} position={[1.336, 3.22, -1.589]} rotation={[0, 1.561, 0]} scale={[0.204, 0.007, 0.01]} />
        <mesh name="Cube146" geometry={nodes.Cube146.geometry} material={nodes.Cube146.material} position={[1.336, 2.906, -1.589]} rotation={[0, 1.561, 0]} scale={[0.206, 0.007, 0.01]} />
        <mesh name="Cube147" geometry={nodes.Cube147.geometry} material={nodes.Cube147.material} position={[1.336, 2.591, -1.59]} rotation={[0, 1.561, 0]} scale={[0.203, 0.007, 0.01]} />
        <mesh name="Cube148" geometry={nodes.Cube148.geometry} material={nodes.Cube148.material} position={[1.336, 2.276, -1.589]} rotation={[0, 1.561, 0]} scale={[0.203, 0.007, 0.01]} />
        <mesh name="Cube149" geometry={nodes.Cube149.geometry} material={nodes.Cube149.material} position={[1.336, 1.965, -1.59]} rotation={[0, 1.561, 0]} scale={[0.204, 0.007, 0.01]} />
        <mesh name="Cube150" geometry={nodes.Cube150.geometry} material={nodes.Cube150.material} position={[1.336, 1.656, -1.588]} rotation={[0, 1.561, 0]} scale={[0.208, 0.007, 0.01]} />
        <mesh name="Cube151" geometry={nodes.Cube151.geometry} material={nodes.Cube151.material} position={[1.336, 1.399, -1.588]} rotation={[0, 1.561, 0]} scale={[0.205, 0.007, 0.01]} />
        <mesh name="Cube152" geometry={nodes.Cube152.geometry} material={nodes.Cube152.material} position={[1.346, 4.464, -2.7]} rotation={[0, 1.561, 0]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube153" geometry={nodes.Cube153.geometry} material={nodes.Cube153.material} position={[1.346, 4.155, -2.7]} rotation={[0, 1.561, 0]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube154" geometry={nodes.Cube154.geometry} material={nodes.Cube154.material} position={[1.346, 3.839, -2.7]} rotation={[0, 1.561, 0]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube155" geometry={nodes.Cube155.geometry} material={nodes.Cube155.material} position={[1.346, 3.526, -2.7]} rotation={[0, 1.561, 0]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube156" geometry={nodes.Cube156.geometry} material={nodes.Cube156.material} position={[1.346, 3.221, -2.7]} rotation={[0, 1.561, 0]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube157" geometry={nodes.Cube157.geometry} material={nodes.Cube157.material} position={[1.346, 2.907, -2.7]} rotation={[0, 1.561, 0]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube158" geometry={nodes.Cube158.geometry} material={nodes.Cube158.material} position={[1.346, 2.594, -2.7]} rotation={[0, 1.561, 0]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube159" geometry={nodes.Cube159.geometry} material={nodes.Cube159.material} position={[1.346, 2.276, -2.7]} rotation={[0, 1.561, 0]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube160" geometry={nodes.Cube160.geometry} material={nodes.Cube160.material} position={[1.346, 1.97, -2.7]} rotation={[0, 1.561, 0]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube161" geometry={nodes.Cube161.geometry} material={nodes.Cube161.material} position={[1.346, 1.657, -2.7]} rotation={[0, 1.561, 0]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube162" geometry={nodes.Cube162.geometry} material={nodes.Cube162.material} position={[1.346, 1.399, -2.7]} rotation={[0, 1.561, 0]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube163" geometry={nodes.Cube163.geometry} material={nodes.Cube163.material} position={[-1.365, 4.461, -2.792]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube164" geometry={nodes.Cube164.geometry} material={nodes.Cube164.material} position={[-1.365, 4.153, -2.792]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube165" geometry={nodes.Cube165.geometry} material={nodes.Cube165.material} position={[-1.365, 3.835, -2.792]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube166" geometry={nodes.Cube166.geometry} material={nodes.Cube166.material} position={[-1.365, 3.523, -2.792]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube167" geometry={nodes.Cube167.geometry} material={nodes.Cube167.material} position={[-1.365, 3.221, -2.792]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube168" geometry={nodes.Cube168.geometry} material={nodes.Cube168.material} position={[-1.365, 2.904, -2.792]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube169" geometry={nodes.Cube169.geometry} material={nodes.Cube169.material} position={[-1.365, 2.59, -2.792]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube170" geometry={nodes.Cube170.geometry} material={nodes.Cube170.material} position={[-1.365, 2.275, -2.792]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube171" geometry={nodes.Cube171.geometry} material={nodes.Cube171.material} position={[-1.365, 1.965, -2.792]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube172" geometry={nodes.Cube172.geometry} material={nodes.Cube172.material} position={[-1.365, 1.654, -2.792]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube173" geometry={nodes.Cube173.geometry} material={nodes.Cube173.material} position={[-1.365, 1.399, -2.792]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.256, 0.007, 0.01]} />
        <mesh name="Cube174" geometry={nodes.Cube174.geometry} material={nodes.Cube174.material} position={[-1.367, 4.461, -1.762]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.206, 0.007, 0.01]} />
        <mesh name="Cube175" geometry={nodes.Cube175.geometry} material={nodes.Cube175.material} position={[-1.367, 4.152, -1.761]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.201, 0.007, 0.01]} />
        <mesh name="Cube176" geometry={nodes.Cube176.geometry} material={nodes.Cube176.material} position={[-1.367, 3.837, -1.76]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.201, 0.007, 0.01]} />
        <mesh name="Cube177" geometry={nodes.Cube177.geometry} material={nodes.Cube177.material} position={[-1.367, 3.522, -1.76]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.2, 0.007, 0.01]} />
        <mesh name="Cube178" geometry={nodes.Cube178.geometry} material={nodes.Cube178.material} position={[-1.367, 3.22, -1.76]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.204, 0.007, 0.01]} />
        <mesh name="Cube179" geometry={nodes.Cube179.geometry} material={nodes.Cube179.material} position={[-1.367, 2.906, -1.76]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.206, 0.007, 0.01]} />
        <mesh name="Cube180" geometry={nodes.Cube180.geometry} material={nodes.Cube180.material} position={[-1.367, 2.591, -1.759]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.203, 0.007, 0.01]} />
        <mesh name="Cube181" geometry={nodes.Cube181.geometry} material={nodes.Cube181.material} position={[-1.367, 2.276, -1.76]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.203, 0.007, 0.01]} />
        <mesh name="Cube182" geometry={nodes.Cube182.geometry} material={nodes.Cube182.material} position={[-1.367, 1.965, -1.759]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.204, 0.007, 0.01]} />
        <mesh name="Cube183" geometry={nodes.Cube183.geometry} material={nodes.Cube183.material} position={[-1.367, 1.656, -1.761]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.208, 0.007, 0.01]} />
        <mesh name="Cube184" geometry={nodes.Cube184.geometry} material={nodes.Cube184.material} position={[-1.367, 1.399, -1.761]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.205, 0.007, 0.01]} />
        <mesh name="Cube185" geometry={nodes.Cube185.geometry} material={nodes.Cube185.material} position={[-1.368, 4.464, -0.649]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube186" geometry={nodes.Cube186.geometry} material={nodes.Cube186.material} position={[-1.368, 4.155, -0.649]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube187" geometry={nodes.Cube187.geometry} material={nodes.Cube187.material} position={[-1.368, 3.839, -0.649]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube188" geometry={nodes.Cube188.geometry} material={nodes.Cube188.material} position={[-1.368, 3.526, -0.649]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube189" geometry={nodes.Cube189.geometry} material={nodes.Cube189.material} position={[-1.368, 3.221, -0.649]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube190" geometry={nodes.Cube190.geometry} material={nodes.Cube190.material} position={[-1.368, 2.907, -0.649]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube191" geometry={nodes.Cube191.geometry} material={nodes.Cube191.material} position={[-1.368, 2.594, -0.649]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube192" geometry={nodes.Cube192.geometry} material={nodes.Cube192.material} position={[-1.368, 2.276, -0.649]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube193" geometry={nodes.Cube193.geometry} material={nodes.Cube193.material} position={[-1.368, 1.97, -0.649]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube194" geometry={nodes.Cube194.geometry} material={nodes.Cube194.material} position={[-1.368, 1.657, -0.649]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube195" geometry={nodes.Cube195.geometry} material={nodes.Cube195.material} position={[-1.368, 1.399, -0.649]} rotation={[Math.PI, -1.569, Math.PI]} scale={[0.347, 0.007, 0.01]} />
        <mesh name="Cube196" geometry={nodes.Cube196.geometry} material={nodes.Cube196.material} position={[1.179, 4.461, -2.083]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube197" geometry={nodes.Cube197.geometry} material={nodes.Cube197.material} position={[1.179, 4.152, -2.083]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube198" geometry={nodes.Cube198.geometry} material={nodes.Cube198.material} position={[1.179, 3.838, -2.083]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube199" geometry={nodes.Cube199.geometry} material={nodes.Cube199.material} position={[1.179, 3.524, -2.083]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube200" geometry={nodes.Cube200.geometry} material={nodes.Cube200.material} position={[1.179, 3.219, -2.083]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube201" geometry={nodes.Cube201.geometry} material={nodes.Cube201.material} position={[1.179, 2.905, -2.083]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube202" geometry={nodes.Cube202.geometry} material={nodes.Cube202.material} position={[1.179, 2.589, -2.083]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube203" geometry={nodes.Cube203.geometry} material={nodes.Cube203.material} position={[1.179, 2.274, -2.083]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube204" geometry={nodes.Cube204.geometry} material={nodes.Cube204.material} position={[1.179, 1.964, -2.083]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube205" geometry={nodes.Cube205.geometry} material={nodes.Cube205.material} position={[1.179, 1.654, -2.083]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube206" geometry={nodes.Cube206.geometry} material={nodes.Cube206.material} position={[1.179, 1.399, -2.083]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube207" geometry={nodes.Cube207.geometry} material={nodes.Cube207.material} position={[1.187, 4.463, -1.108]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube208" geometry={nodes.Cube208.geometry} material={nodes.Cube208.material} position={[1.187, 4.156, -1.108]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube209" geometry={nodes.Cube209.geometry} material={nodes.Cube209.material} position={[1.187, 3.84, -1.108]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube210" geometry={nodes.Cube210.geometry} material={nodes.Cube210.material} position={[1.187, 3.526, -1.108]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube211" geometry={nodes.Cube211.geometry} material={nodes.Cube211.material} position={[1.187, 3.221, -1.108]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube212" geometry={nodes.Cube212.geometry} material={nodes.Cube212.material} position={[1.187, 2.907, -1.108]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube213" geometry={nodes.Cube213.geometry} material={nodes.Cube213.material} position={[1.187, 2.592, -1.108]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube214" geometry={nodes.Cube214.geometry} material={nodes.Cube214.material} position={[1.187, 2.276, -1.108]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube215" geometry={nodes.Cube215.geometry} material={nodes.Cube215.material} position={[1.187, 1.967, -1.108]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube216" geometry={nodes.Cube216.geometry} material={nodes.Cube216.material} position={[1.187, 1.656, -1.108]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube217" geometry={nodes.Cube217.geometry} material={nodes.Cube217.material} position={[1.187, 1.399, -1.108]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube218" geometry={nodes.Cube218.geometry} material={nodes.Cube218.material} position={[-1.226, 4.461, -2.243]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube219" geometry={nodes.Cube219.geometry} material={nodes.Cube219.material} position={[-1.226, 4.152, -2.243]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube220" geometry={nodes.Cube220.geometry} material={nodes.Cube220.material} position={[-1.226, 3.838, -2.243]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube221" geometry={nodes.Cube221.geometry} material={nodes.Cube221.material} position={[-1.226, 3.524, -2.243]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube222" geometry={nodes.Cube222.geometry} material={nodes.Cube222.material} position={[-1.226, 3.219, -2.243]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube223" geometry={nodes.Cube223.geometry} material={nodes.Cube223.material} position={[-1.226, 2.905, -2.243]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube224" geometry={nodes.Cube224.geometry} material={nodes.Cube224.material} position={[-1.226, 2.589, -2.243]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube225" geometry={nodes.Cube225.geometry} material={nodes.Cube225.material} position={[-1.226, 2.274, -2.243]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube226" geometry={nodes.Cube226.geometry} material={nodes.Cube226.material} position={[-1.226, 1.964, -2.243]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube227" geometry={nodes.Cube227.geometry} material={nodes.Cube227.material} position={[-1.226, 1.654, -2.243]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube228" geometry={nodes.Cube228.geometry} material={nodes.Cube228.material} position={[-1.226, 1.399, -2.243]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube229" geometry={nodes.Cube229.geometry} material={nodes.Cube229.material} position={[-1.25, 4.463, -1.267]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube230" geometry={nodes.Cube230.geometry} material={nodes.Cube230.material} position={[-1.25, 4.156, -1.267]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube231" geometry={nodes.Cube231.geometry} material={nodes.Cube231.material} position={[-1.25, 3.84, -1.267]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube232" geometry={nodes.Cube232.geometry} material={nodes.Cube232.material} position={[-1.25, 3.526, -1.267]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube233" geometry={nodes.Cube233.geometry} material={nodes.Cube233.material} position={[-1.25, 3.221, -1.267]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube234" geometry={nodes.Cube234.geometry} material={nodes.Cube234.material} position={[-1.25, 2.907, -1.267]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube235" geometry={nodes.Cube235.geometry} material={nodes.Cube235.material} position={[-1.25, 2.592, -1.267]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube236" geometry={nodes.Cube236.geometry} material={nodes.Cube236.material} position={[-1.25, 2.276, -1.267]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube237" geometry={nodes.Cube237.geometry} material={nodes.Cube237.material} position={[-1.25, 1.967, -1.267]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube238" geometry={nodes.Cube238.geometry} material={nodes.Cube238.material} position={[-1.25, 1.656, -1.267]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Cube239" geometry={nodes.Cube239.geometry} material={nodes.Cube239.material} position={[-1.25, 1.399, -1.267]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[0.275, 0.007, 0.01]} />
        <mesh name="Plane037" geometry={nodes.Plane037.geometry} material={materials['Material.010']} position={[0.904, 4.833, -0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.057} />
        <mesh name="Plane038" geometry={nodes.Plane038.geometry} material={nodes.Plane038.material} position={[0.904, 4.833, -0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.057} />
        <mesh name="Plane039" geometry={nodes.Plane039.geometry} material={materials['Material.009']} position={[0.904, 4.833, -0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.057} />
        <mesh name="Plane040" geometry={nodes.Plane040.geometry} material={materials['Material.011']} position={[0.904, 4.833, -0.177]} rotation={[Math.PI / 2, 0, 0]} scale={0.057} />
        <mesh name="Plane041" geometry={nodes.Plane041.geometry} material={materials['Material.008']} position={[0.906, 4.908, -0.178]} rotation={[Math.PI / 2, 0, 0]} scale={0.182} />
        <mesh name="Plane042" geometry={nodes.Plane042.geometry} material={nodes.Plane042.material} position={[0.904, 4.795, -0.191]} rotation={[Math.PI / 2, 0, 0]} scale={0.057} />
        <mesh name="Plane043" geometry={nodes.Plane043.geometry} material={nodes.Plane043.material} position={[0.909, 4.507, -0.177]} rotation={[-Math.PI, 0.018, -Math.PI]} scale={0.182} />
        <mesh name="Plane044" geometry={nodes.Plane044.geometry} material={materials.Material} position={[-0.901, 1.145, 0.046]} rotation={[Math.PI / 2, 0, 0]} scale={0.049} />
        <group name="Rusty_Lamp" position={[-1.402, 0.342, 0.571]} rotation={[Math.PI / 2, 0, 0]} scale={0.856}>
          <mesh name="mesh010" geometry={nodes.mesh010.geometry} material={materials.Metal} />
          <mesh name="mesh010_1" geometry={nodes.mesh010_1.geometry} material={materials.Inside_Body} />
          <mesh name="Bulb_Base_001" geometry={nodes.Bulb_Base_001.geometry} material={materials.Metal} />
          <mesh name="Bulb_Socket1_001" geometry={nodes.Bulb_Socket1_001.geometry} material={materials.Metal} />
          <mesh name="Bulb_Socket2_001" geometry={nodes.Bulb_Socket2_001.geometry} material={materials.Metal} />
          <mesh name="Circle_001" geometry={nodes.Circle_001.geometry} material={materials.Metal} />
          <mesh name="Circle_001_001" geometry={nodes.Circle_001_001.geometry} material={materials.Metal} />
          <mesh name="Cube_003" geometry={nodes.Cube_003.geometry} material={materials.Metal} />
          <mesh name="Cube_004" geometry={nodes.Cube_004.geometry} material={materials.Metal} />
          <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.Metal} />
          <mesh name="Cylinder_001" geometry={nodes.Cylinder_001.geometry} material={materials.Metal} />
          <mesh name="Retopo_Bulb" geometry={nodes.Retopo_Bulb.geometry} material={materials.Glass} />
          <mesh name="Retopo_Bulb_Holder_001" geometry={nodes.Retopo_Bulb_Holder_001.geometry} material={materials.Metal} />
          <mesh name="Retopo_Cylinder_006" geometry={nodes.Retopo_Cylinder_006.geometry} material={materials.Glass} />
          <mesh name="Retopo_NurbsPath_002_002_001" geometry={nodes.Retopo_NurbsPath_002_002_001.geometry} material={materials.Glass_001} />
        </group>
        <group name="Rusty_Lamp001" position={[-2.235, 0.342, 0.571]} rotation={[Math.PI / 2, 0, 0]} scale={0.856}>
          <mesh name="mesh001" geometry={nodes.mesh001.geometry} material={materials.Metal} />
          <mesh name="mesh001_1" geometry={nodes.mesh001_1.geometry} material={materials.Inside_Body} />
          <mesh name="Retopo_Bulb001" geometry={nodes.Retopo_Bulb001.geometry} material={materials.Glass} />
        </group>
        <group name="Rusty_Lamp002" position={[-2.235, 0.342, -0.123]} rotation={[Math.PI / 2, 0, 0]} scale={0.856}>
          <mesh name="mesh003" geometry={nodes.mesh003.geometry} material={materials.Metal} />
          <mesh name="mesh003_1" geometry={nodes.mesh003_1.geometry} material={materials.Inside_Body} />
          <mesh name="Retopo_Bulb002" geometry={nodes.Retopo_Bulb002.geometry} material={materials.Glass} />
        </group>
        <group name="Rusty_Lamp004" position={[2.254, 0.342, -0.123]} rotation={[Math.PI / 2, 0, 0]} scale={0.856}>
          <mesh name="mesh009" geometry={nodes.mesh009.geometry} material={materials.Metal} />
          <mesh name="mesh009_1" geometry={nodes.mesh009_1.geometry} material={materials.Inside_Body} />
          <mesh name="Retopo_Bulb004" geometry={nodes.Retopo_Bulb004.geometry} material={materials.Glass} />
        </group>
        <group name="Rusty_Lamp003" position={[2.254, 0.342, 0.565]} rotation={[Math.PI / 2, 0, 0]} scale={0.856}>
          <mesh name="mesh014" geometry={nodes.mesh014.geometry} material={materials.Metal} />
          <mesh name="mesh014_1" geometry={nodes.mesh014_1.geometry} material={materials.Inside_Body} />
        </group>
        <group name="Rusty_Lamp005" position={[1.365, 0.342, 0.565]} rotation={[Math.PI / 2, 0, 0]} scale={0.856}>
          <mesh name="mesh015" geometry={nodes.mesh015.geometry} material={materials.Metal} />
          <mesh name="mesh015_1" geometry={nodes.mesh015_1.geometry} material={materials.Inside_Body} />
        </group>
        <group name="Street_lamp" position={[0, 0, 1.71]} scale={[0.97, 1, 1]}>
          <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials.WH_metal} />
          <mesh name="Cylinder005_1" geometry={nodes.Cylinder005_1.geometry} material={materials.WH_light01} />
          <mesh name="Cylinder005_2" geometry={nodes.Cylinder005_2.geometry} material={materials.WH_metal2} />
        </group>
        <group name="Tree_LOD_2012" position={[-7.087, 0, 2.378]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.126}>
          <mesh name="tree012" geometry={nodes.tree012.geometry} material={materials.bark} />
          <mesh name="tree012_1" geometry={nodes.tree012_1.geometry} material={materials.leaf} />
        </group>
        <mesh name="Iron_Gate001" geometry={nodes.Iron_Gate001.geometry} material={materials['Cast Iron']} position={[-2.127, 0.268, 0.84]} rotation={[0, -0.004, 0]} scale={[0.153, 0.177, 0.165]} />
        <mesh name="Iron_Gate" geometry={nodes.Iron_Gate.geometry} material={materials['Cast Iron']} position={[-1.512, 0.268, 0.84]} rotation={[-Math.PI, 0.015, -Math.PI]} scale={[0.139, 0.177, 0.166]} />
        <group name="Gate_post" position={[-2.168, 0.301, 0.84]} scale={[0.147, 0.177, 0.177]}>
          <mesh name="Plane117_1" geometry={nodes.Plane117_1.geometry} material={materials['Painted Metal Rubbish Bin Green']} />
          <mesh name="Plane117_2" geometry={nodes.Plane117_2.geometry} material={materials['Cast Iron Blanched With Rust']} />
        </group>
        <mesh name="Iron_Gate002" geometry={nodes.Iron_Gate002.geometry} material={materials['Cast Iron']} position={[1.48, 0.268, 0.84]} rotation={[0, 1.425, 0]} scale={[0.152, 0.177, 0.165]} />
        <mesh name="Iron_Gate003" geometry={nodes.Iron_Gate003.geometry} material={materials['Cast Iron']} position={[2.108, 0.268, 0.84]} rotation={[-Math.PI, 1.416, -Math.PI]} scale={[0.149, 0.177, 0.166]} />
        <group name="Gate_post002" position={[1.438, 0.301, 0.84]} scale={[0.15, 0.177, 0.177]}>
          <mesh name="Plane119_1" geometry={nodes.Plane119_1.geometry} material={materials['Painted Metal Rubbish Bin Green']} />
          <mesh name="Plane119_2" geometry={nodes.Plane119_2.geometry} material={materials['Cast Iron Blanched With Rust']} />
        </group>
        <group name="gate_small_001wall001" position={[1.403, 0.367, -1.807]} rotation={[0, 1.571, 0]} scale={0.133}>
          <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['stone.001']} />
          <mesh name="Circle003_1" geometry={nodes.Circle003_1.geometry} material={materials['stone.dark.001']} />
          <mesh name="Circle003_2" geometry={nodes.Circle003_2.geometry} material={materials['plain.001']} />
        </group>
        <group name="gate_small_001001" position={[1.403, 0.367, -1.807]} rotation={[0, 1.571, 0]} scale={0.133}>
          <mesh name="Plane010_1" geometry={nodes.Plane010_1.geometry} material={materials['metal.dark.001']} />
          <mesh name="Plane010_2" geometry={nodes.Plane010_2.geometry} material={materials['brass.001']} />
          <mesh name="Plane010_3" geometry={nodes.Plane010_3.geometry} material={materials['wood.001']} />
          <mesh name="Plane010_4" geometry={nodes.Plane010_4.geometry} material={materials['glass.001']} />
        </group>
        <group name="camera001" position={[5.458, 0.084, 19.801]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.002}>
          <mesh name="Cube264" geometry={nodes.Cube264.geometry} material={materials['Piano Black With Fingerprints Plastic PL.002']} />
          <mesh name="Cube264_1" geometry={nodes.Cube264_1.geometry} material={materials['Steel.002']} />
        </group>
        <mesh name="LADA_2107LOGO" geometry={nodes.LADA_2107LOGO.geometry} material={materials['LADA 2107']} position={[1.04, 0.016, 1.958]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={0.196} />
        <group name="gate_small_001wall" position={[-1.469, 0.418, -0.372]} rotation={[0, 1.571, 0]} scale={0.164}>
          <mesh name="Circle000" geometry={nodes.Circle000.geometry} material={materials.stone} />
          <mesh name="Circle000_1" geometry={nodes.Circle000_1.geometry} material={materials['stone.dark']} />
          <mesh name="Circle000_2" geometry={nodes.Circle000_2.geometry} material={materials.plain} />
        </group>
        <group name="gate_small_001" position={[-1.489, 0.418, -0.372]} rotation={[0, 1.571, 0]} scale={0.164}>
          <mesh name="Plane121_1" geometry={nodes.Plane121_1.geometry} material={materials['metal.dark']} />
          <mesh name="Plane121_2" geometry={nodes.Plane121_2.geometry} material={materials.brass} />
          <mesh name="Plane121_3" geometry={nodes.Plane121_3.geometry} material={materials.wood} />
          <mesh name="Plane121_4" geometry={nodes.Plane121_4.geometry} material={materials.glass} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/abcd.glb')
